import { prisma } from "@/lib/prisma";

const EQUIPEMNT_SEEDS = [
  // Weapons
  {
    range: "+2",
    size: "8/10",
    damage: "+30",
    defense: "+7",
    type: "weapon",
    attributes: "",
    weight: "75 oz",
    dropBy: "Troll",
    rarity: "common",
    sellTo: "350 gp",
    category: "sword",
    attackSpeed: "-2",
    name: "Broadsword",
    buyFrom: "Weapon Master",
    imageUrl: "/swords/Broadsword.webp",
  },
  {
    range: "+2",
    size: "8/10",
    damage: "+25",
    defense: "+3",
    type: "weapon",
    attributes: "",
    rarity: "magic",
    weight: "70 oz",
    dropBy: "Troll",
    sellTo: "300 gp",
    category: "sword",
    attackSpeed: "+3",
    name: "Cutlass Sword",
    buyFrom: "Weapon Master",
    imageUrl: "/swords/Cutlass_sword.webp",
  },
  {
    range: "+2",
    size: "8/10",
    damage: "+35",
    type: "weapon",
    defense: "+10",
    attributes: "",
    weight: "80 oz",
    dropBy: "Knight",
    sellTo: "400 gp",
    category: "sword",
    attackSpeed: "+2",
    name: "Epee Sword",
    rarity: "legendary",
    buyFrom: "Royal Armory",
    imageUrl: "/swords/Epee_sword.webp",
  },
  {
    range: "+2",
    size: "6/10",
    damage: "+15",
    defense: "+2",
    type: "weapon",
    attributes: "",
    weight: "36 oz",
    sellTo: "150 gp",
    category: "sword",
    attackSpeed: "+4",
    name: "Iron Sword",
    rarity: "legendary",
    dropBy: "Orc Warrior",
    buyFrom: "Blacksmith",
    imageUrl: "/swords/Ironsword.webp",
  },
  {
    range: "+7",
    size: "8/10",
    damage: "+40",
    type: "weapon",
    defense: "+10",
    attributes: "",
    weight: "98 oz",
    dropBy: "Knight",
    sellTo: "500 gp",
    category: "sword",
    attackSpeed: "+1",
    name: "Long Sword",
    rarity: "legendary",
    buyFrom: "Royal Armory",
    imageUrl: "/swords/Longsword.webp",
  },
  {
    range: "+2",
    damage: "+8",
    size: "6/10",
    defense: "+2",
    type: "weapon",
    attributes: "",
    weight: "30 oz",
    sellTo: "75 gp",
    category: "sword",
    attackSpeed: "+2",
    dropBy: "Skeleton",
    name: "Rusty Sword",
    rarity: "legendary",
    buyFrom: "Weapon Shop",
    imageUrl: "/swords/Rusty_sword.webp",
  },
  {
    range: "+2",
    size: "8/10",
    damage: "+30",
    type: "weapon",
    defense: "+10",
    attributes: "",
    weight: "80 oz",
    dropBy: "Knight",
    sellTo: "400 gp",
    category: "sword",
    attackSpeed: "+2",
    rarity: "legendary",
    name: "Serpent Sword",
    buyFrom: "Royal Armory",
    imageUrl: "/swords/Serpent_Sword.webp",
  },
  {
    range: "+2",
    size: "8/10",
    name: "Sword",
    damage: "+20",
    defense: "+5",
    type: "weapon",
    attributes: "",
    weight: "70 oz",
    dropBy: "Troll",
    sellTo: "300 gp",
    category: "sword",
    attackSpeed: "+3",
    rarity: "legendary",
    buyFrom: "Weapon Master",
    imageUrl: "/swords/Sword3.webp",
  },
  {
    range: "+2",
    size: "8/10",
    name: "Sword",
    damage: "+25",
    type: "weapon",
    defense: "+10",
    attributes: "",
    weight: "75 oz",
    dropBy: "Troll",
    sellTo: "350 gp",
    category: "sword",
    attackSpeed: "+2",
    rarity: "legendary",
    buyFrom: "Weapon Master",
    imageUrl: "/swords/Sword4.webp",
  },
  {
    range: "+2",
    size: "8/10",
    name: "Sword",
    damage: "+30",
    type: "weapon",
    defense: "+10",
    attributes: "",
    weight: "80 oz",
    dropBy: "Knight",
    sellTo: "400 gp",
    category: "sword",
    attackSpeed: "+1",
    rarity: "legendary",
    buyFrom: "Royal Armory",
    imageUrl: "/swords/Sword6.webp",
  },

  // Dagger
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    rarity: "common",
    dropBy: "Goblin",
    attackSpeed: "+3",
    name: "Bone Knife",
    category: "dagger",
    buyFrom: "Blacksmith",
    imageUrl: "/daggers/Bone_Knife.webp",
  },
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    name: "Dagger",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    rarity: "magic",
    sellTo: "50 gp",
    dropBy: "Goblin",
    attackSpeed: "+3",
    category: "dagger",
    buyFrom: "Blacksmith",
    imageUrl: "/daggers/Dagger3.webp",
  },
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    name: "Knife",
    rarity: "rare",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    attackSpeed: "+3",
    category: "dagger",
    buyFrom: "Blacksmith",
    imageUrl: "/daggers/Knife.png",
  },
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    rarity: "rare",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    attackSpeed: "+3",
    category: "dagger",
    name: "Onyx Dagger",
    buyFrom: "Blacksmith",
    imageUrl: "/daggers/Onyx_Dagger.webp",
  },
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    rarity: "rare",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    attackSpeed: "+3",
    category: "dagger",
    name: "Silver Dagger",
    buyFrom: "Blacksmith",
    imageUrl: "/daggers/Silver_Dagger.webp",
  },

  // Bows
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    category: "bow",
    sellTo: "50 gp",
    name: "Bone Bow",
    rarity: "common",
    dropBy: "Goblin",
    attackSpeed: "+3",
    buyFrom: "Blacksmith",
    imageUrl: "/bow/Bone_Bow.webp",
  },
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    rarity: "magic",
    category: "bow",
    sellTo: "50 gp",
    name: "Long Bow",
    dropBy: "Goblin",
    attackSpeed: "+3",
    buyFrom: "Blacksmith",
    imageUrl: "/bow/Longbow.webp",
  },
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    category: "bow",
    sellTo: "50 gp",
    dropBy: "Goblin",
    name: "Stone Bow",
    attackSpeed: "+3",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/bow/StoneBow.webp",
  },
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    category: "bow",
    sellTo: "50 gp",
    dropBy: "Goblin",
    attackSpeed: "+3",
    name: "Wooden Bow",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/bow/Wooden_Bow.webp",
  },

  // Staffs
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    rarity: "common",
    dropBy: "Goblin",
    category: "staff",
    attackSpeed: "+3",
    name: "Crystal Staff",
    buyFrom: "Blacksmith",
    imageUrl: "/staff/Crystal_Staff.webp",
  },
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    rarity: "magic",
    sellTo: "50 gp",
    name: "Orb blue",
    dropBy: "Goblin",
    category: "staff",
    attackSpeed: "+3",
    buyFrom: "Blacksmith",
    imageUrl: "/staff/Orb_blue.webp",
  },
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    name: "Orb green",
    category: "staff",
    attackSpeed: "+3",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/staff/Orb_green.webp",
  },
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    name: "Orb red",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "staff",
    attackSpeed: "+3",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/staff/Orb_red.webp",
  },
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "staff",
    attackSpeed: "+3",
    rarity: "legendary",
    name: "Wooden Staff",
    buyFrom: "Blacksmith",
    imageUrl: "/staff/Wooden_staff.webp",
  },

  // Shields
  {
    defense: "",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    rarity: "common",
    dropBy: "Goblin",
    category: "shield",
    buyFrom: "Blacksmith",
    name: "Buckler Shield",
    imageUrl: "/shield/Buckler_shield.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    rarity: "magic",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "shield",
    name: "Plated Shield",
    buyFrom: "Blacksmith",
    imageUrl: "/shield/Plated_Shield.webp",
  },
  {
    defense: "",
    size: "2/10",
    rarity: "rare",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "shield",
    name: "Brass Shield",
    buyFrom: "Blacksmith",
    imageUrl: "/shield/Shield5.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "shield",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    name: "Studded Shield",
    imageUrl: "/shield/Studded_shield.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "shield",
    rarity: "legendary",
    name: "Tower Shield",
    buyFrom: "Blacksmith",
    imageUrl: "/shield/Tower_Shield.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "shield",
    rarity: "legendary",
    name: "Wooden Shield",
    buyFrom: "Blacksmith",
    imageUrl: "/shield/Wooden_shield.webp",
  },

  // Gloves
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    rarity: "common",
    dropBy: "Goblin",
    category: "glove",
    attackSpeed: "+3",
    name: "Cloth Gloves",
    buyFrom: "Blacksmith",
    imageUrl: "/gloves/Cloth_gloves.webp",
  },
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    rarity: "magic",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "glove",
    attackSpeed: "+3",
    buyFrom: "Blacksmith",
    name: "Leather Gloves",
    imageUrl: "/gloves/Leather_gloves.webp",
  },
  {
    range: "",
    defense: "",
    damage: "+3",
    size: "2/10",
    rarity: "rare",
    type: "weapon",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "glove",
    attackSpeed: "+3",
    name: "Plate Gloves",
    buyFrom: "Blacksmith",
    imageUrl: "/gloves/Plate_gloves.webp",
  },

  // Chest
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    rarity: "magic",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "chest",
    name: "Brass Armor",
    buyFrom: "Blacksmith",
    imageUrl: "/armor/Brass_armor.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    rarity: "rare",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "chest",
    buyFrom: "Blacksmith",
    name: "Brigandine Vest",
    imageUrl: "/armor/Brigandine_Vest.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "chest",
    name: "Chain Armor",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/armor/Chain_armor.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "chest",
    name: "Cloth Armor",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/armor/Cloth_armor.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "chest",
    name: "Cloth Vest",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/armor/Cloth_Vest.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "chest",
    rarity: "legendary",
    name: "Crooked Vest",
    buyFrom: "Blacksmith",
    imageUrl: "/armor/Crooked_Vest.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    name: "Dark Robe",
    category: "chest",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/armor/Dark_Robe.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "chest",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    name: "Gambeson Armor",
    imageUrl: "/armor/Gambeson_armor.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "chest",
    rarity: "legendary",
    name: "Leather Cloak",
    buyFrom: "Blacksmith",
    imageUrl: "/armor/Leather_Cloak.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "chest",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    name: "Nightshade Robe",
    imageUrl: "/armor/Nightshade_Robe.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "chest",
    name: "Plate Armor",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/armor/Plate_armor.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "chest",
    name: "Royal Armor",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/armor/Royal_Armor.webp",
  },

  // Helmets
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    rarity: "common",
    dropBy: "Goblin",
    name: "Druid Hat",
    category: "helmet",
    buyFrom: "Blacksmith",
    imageUrl: "/helmet/Druid_hat.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    rarity: "magic",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "helmet",
    name: "Mask Helmet",
    buyFrom: "Blacksmith",
    imageUrl: "/helmet/Helmet3.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    rarity: "rare",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "helmet",
    buyFrom: "Blacksmith",
    name: "Mage Leather Hat",
    imageUrl: "/helmet/Helmet5.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "helmet",
    rarity: "legendary",
    name: "Kettle Helmet",
    buyFrom: "Blacksmith",
    imageUrl: "/helmet/Kettle_helmet.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "helmet",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    name: "Leather Helmet",
    imageUrl: "/helmet/Leather_helmet1.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "helmet",
    rarity: "legendary",
    name: "Leather Hood",
    buyFrom: "Blacksmith",
    imageUrl: "/helmet/Leather_hood.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    name: "Mage Hat",
    dropBy: "Goblin",
    category: "helmet",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/helmet/Mage_hat1.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    name: "Mage Hood",
    category: "helmet",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/helmet/Mage_hood.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "helmet",
    rarity: "legendary",
    name: "Plate Helmet",
    buyFrom: "Blacksmith",
    imageUrl: "/helmet/Plate_helmet.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "helmet",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    name: "Spanghen Helmet",
    imageUrl: "/helmet/Spanghen_helmet.webp",
  },

  // Boots
  {
    defense: "",
    size: "2/10",
    name: "Boots",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    rarity: "common",
    category: "boot",
    dropBy: "Goblin",
    buyFrom: "Blacksmith",
    imageUrl: "/boots/Boots1.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    rarity: "magic",
    sellTo: "50 gp",
    category: "boot",
    dropBy: "Goblin",
    name: "Leather Boots",
    buyFrom: "Blacksmith",
    imageUrl: "/boots/Leather_boots.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    rarity: "rare",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    category: "boot",
    dropBy: "Goblin",
    name: "Plate Boots",
    buyFrom: "Blacksmith",
    imageUrl: "/boots/Plate_boots.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    category: "boot",
    dropBy: "Goblin",
    name: "Quoki Shoes",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/boots/Quoki_Shoes.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    category: "boot",
    dropBy: "Goblin",
    rarity: "legendary",
    name: "Sailor Boots",
    buyFrom: "Blacksmith",
    imageUrl: "/boots/Sailor_Boots.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    category: "boot",
    dropBy: "Goblin",
    rarity: "legendary",
    name: "Winged Boots",
    buyFrom: "Blacksmith",
    imageUrl: "/boots/Winged_Boots.webp",
  },

  // Legs
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    category: "leg",
    sellTo: "50 gp",
    rarity: "common",
    dropBy: "Goblin",
    name: "Brass Legs",
    buyFrom: "Blacksmith",
    imageUrl: "/legs/Brass_Legs.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    rarity: "magic",
    category: "leg",
    sellTo: "50 gp",
    dropBy: "Goblin",
    buyFrom: "Blacksmith",
    name: "Brigandine Legs",
    imageUrl: "/legs/Brigandine_Legs.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    rarity: "rare",
    attributes: "",
    weight: "8 oz",
    category: "leg",
    sellTo: "50 gp",
    dropBy: "Goblin",
    name: "Burlap Skirt",
    buyFrom: "Blacksmith",
    imageUrl: "/legs/Burlap_Skirt.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    category: "leg",
    sellTo: "50 gp",
    dropBy: "Goblin",
    name: "Cloth Pants",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/legs/Cloth_Pants.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    category: "leg",
    sellTo: "50 gp",
    dropBy: "Goblin",
    name: "Euler Pants",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/legs/Euler_Pants.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    category: "leg",
    sellTo: "50 gp",
    dropBy: "Goblin",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    name: "Leather Cuisse",
    imageUrl: "/legs/Leather_Cuisse.webp",
  },
  {
    defense: "",
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    category: "leg",
    sellTo: "50 gp",
    dropBy: "Goblin",
    name: "Plate Legs",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/legs/Plate_legs.webp",
  },

  // Rings
  {
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    rarity: "common",
    category: "ring",
    dropBy: "Goblin",
    name: "Crystal Ring",
    buyFrom: "Blacksmith",
    imageUrl: "/ring/Crystal_Ring.webp",
  },
  {
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    rarity: "magic",
    sellTo: "50 gp",
    category: "ring",
    dropBy: "Goblin",
    name: "Death Ring",
    buyFrom: "Blacksmith",
    imageUrl: "/ring/Death_ring.webp",
  },
  {
    size: "2/10",
    type: "armor",
    rarity: "rare",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    category: "ring",
    dropBy: "Goblin",
    name: "Diamond Ring",
    buyFrom: "Blacksmith",
    imageUrl: "/ring/Diamond_Ring.webp",
  },
  {
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    category: "ring",
    dropBy: "Goblin",
    name: "Garnet Ring",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/ring/Garnet_Ring.webp",
  },
  {
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    category: "ring",
    dropBy: "Goblin",
    name: "Golden Ring",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/ring/Golden_ring.webp",
  },
  {
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    category: "ring",
    dropBy: "Goblin",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    name: "Regeeration Ring",
    imageUrl: "/ring/Regeneration_Ring.webp",
  },
  {
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    category: "ring",
    dropBy: "Goblin",
    name: "Silver Ring",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/ring/Silver_Ring.webp",
  },
  {
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    category: "ring",
    dropBy: "Goblin",
    name: "Zircon Ring",
    rarity: "legendary",
    buyFrom: "Blacksmith",
    imageUrl: "/ring/Zircon_Ring.webp",
  },

  // Necklaces
  {
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    rarity: "legendary",
    category: "necklace",
    buyFrom: "Blacksmith",
    name: "Blessed Amulet",
    imageUrl: "/necklace/Blessed_Amulet.webp",
  },
  {
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    rarity: "common",
    dropBy: "Goblin",
    category: "necklace",
    buyFrom: "Blacksmith",
    name: "Leather Collar",
    imageUrl: "/necklace/Leather_Collar.webp",
  },
  {
    size: "2/10",
    type: "armor",
    attributes: "",
    weight: "8 oz",
    rarity: "magic",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "necklace",
    name: "Ruby Necklace",
    buyFrom: "Blacksmith",
    imageUrl: "/necklace/Ruby_necklace.webp",
  },
  {
    size: "2/10",
    name: "Scarf",
    type: "armor",
    rarity: "rare",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "necklace",
    buyFrom: "Blacksmith",
    imageUrl: "/necklace/Scarf.webp",
  },
  {
    size: "2/10",
    type: "armor",
    rarity: "rare",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    category: "necklace",
    name: "Silver amulet",
    buyFrom: "Blacksmith",
    imageUrl: "/necklace/Silver_amulet.webp",
  },

  // Backpacks
  {
    size: "2/10",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    rarity: "common",
    dropBy: "Goblin",
    type: "accessory",
    category: "backpack",
    name: "Backpack Blue",
    buyFrom: "Blacksmith",
    imageUrl: "/backpack/Backpack_blue.webp",
  },
  {
    size: "2/10",
    attributes: "",
    weight: "8 oz",
    rarity: "magic",
    sellTo: "50 gp",
    dropBy: "Goblin",
    type: "accessory",
    category: "backpack",
    buyFrom: "Blacksmith",
    name: "Simple Backpack",
    imageUrl: "/backpack/Simple_Bag.webp",
  },
  {
    size: "2/10",
    rarity: "rare",
    attributes: "",
    weight: "8 oz",
    sellTo: "50 gp",
    dropBy: "Goblin",
    type: "accessory",
    category: "backpack",
    buyFrom: "Blacksmith",
    name: "Backpack Brown",
    imageUrl: "/backpack/Backpack_brown.webp",
  },
];

async function main() {
  console.log("Start seeding...");

  for (const equipment of EQUIPEMNT_SEEDS) {
    await prisma.equipment.create({
      data: {
        ...equipment,
        slot: equipment.category,
      },
    });
  }

  console.log("Seeding finished.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
