export const OTHER_DATABASE = [
  // Drop Creatures
  { name: "Rat Tail", weight: "1.5 oz", sellTo: "5 Gold", type: "drop_creatures", dropBy: "Rat, Giant Rat", imageUrl: "/creature-drops/Rat_tail.webp" },
  { weight: "1 oz", dropBy: "Goblin", sellTo: "4 Gold", name: "Ragged Cloth", type: "drop_creatures", imageUrl: "/creature-drops/Ragged_Cloth.webp" },
  { dropBy: "?", weight: "2.5 oz", sellTo: "1 Gold", name: "Boletus Piece", type: "drop_creatures", imageUrl: "/creature-drops/Boletus_Piece.webp" },
  { dropBy: "?", weight: "1 oz", sellTo: "30 Gold", name: "Colocasia Seed", type: "drop_creatures", imageUrl: "/creature-drops/Colocasia_Seed.webp" },
  { dropBy: "Sheep", weight: "1.1 oz", name: "White Wool", sellTo: "30 Gold?", type: "drop_creatures", imageUrl: "/creature-drops/White_Wool.webp" },
  { sellTo: "?", weight: "1.4 oz", name: "Black Wool", dropBy: "Black Sheep", type: "drop_creatures", imageUrl: "/creature-drops/Black_wool.webp" },
  { dropBy: "?", weight: "1 oz", sellTo: "5 Gold", name: "Slime Essence", type: "drop_creatures", imageUrl: "/creature-drops/Slime_Essence.webp" },
  { dropBy: "?", sellTo: "?", weight: "0.1 oz", name: "Torn Paper", type: "drop_creatures", imageUrl: "/creature-drops/Torn_paper.webp" },
  { sellTo: "?", weight: "4.5 oz", name: "Forsaken Cross", type: "drop_creatures", dropBy: "Occultist Apprentice", imageUrl: "/creature-drops/Forsaken_cross.webp" },
  { weight: "5 oz", sellTo: "1 Gold", dropBy: "Skeleton", name: "Small Skull", type: "drop_creatures", imageUrl: "/creature-drops/Small_Skull.webp" },
  { weight: "7 oz", sellTo: "1 Gold", dropBy: "Skeleton", name: "Small Bones", type: "drop_creatures", imageUrl: "/creature-drops/Small_Bones.webp" },
  { weight: "?", dropBy: "?", sellTo: "?", name: "Bones", type: "drop_creatures", imageUrl: "/creature-drops/Bones.webp" },
  { weight: "", dropBy: "", sellTo: "", name: "Wooden Twigs", type: "drop_creatures", imageUrl: "/creature-drops/Wooden_twigs1.webp" },
  { weight: "1 oz", name: "Old Ring", dropBy: "Goblin", sellTo: "15 Gold", type: "drop_creatures", imageUrl: "/creature-drops/Broken_ring.webp" },
  { dropBy: "?", weight: "0.1 oz", sellTo: "3 Gold", name: "Bug Wings", type: "drop_creatures", imageUrl: "/creature-drops/Bug_wings.webp" },

  // Items Quest
  { name: "Blue Ink", weight: "100 oz", type: "itens_quest", description: "A tail from a rat.", imageUrl: "/quest-items/Blue_Ink.webp" },
  { name: "Herb Bag", weight: "100 oz", type: "itens_quest", description: "A cloth from a ragged.", imageUrl: "/quest-items/Herb_bag.webp" },
  { weight: "100 oz", type: "itens_quest", name: "Potion Aqua Base", description: "A piece from a boletus.", imageUrl: "/quest-items/Aqua_vial_jebidiah.webp" },
  { weight: "100 oz", type: "itens_quest", name: "Jebidiah vials", description: "A seed from a colocasia.", imageUrl: "/quest-items/Jebidiah_vials.webp" },
  { name: "Almanac", weight: "100 oz", type: "itens_quest", description: "A wool from a white.", imageUrl: "/quest-items/Almanac.webp" },

  // Monster
  { hp: "195", exp: "277", abilities: "", type: "monster", name: "Viscid Goblin", loot: "0-2 Gold, Bug Wings" },
  { hp: "1284", exp: "3184", abilities: "", type: "monster", name: "Young Ampitere", loot: "0-25 Gold, Bluegill, Plated Legs, Hook Claw, Dragonfruit, Leather Coif" },
  {
    hp: "685",
    exp: "1208.48",
    type: "monster",
    name: "Cave Troll",
    abilities: "Melee (0-?), Leap (0-?), Ground Slam (0-?)",
    loot: "0-15 Gold, 0-2 Lamb Meat, Brass Legs, Ragged Cloth, Broadsword, Small Skull, Leather Boots, Gambeson",
  },
  { hp: "352", exp: "574.58", abilities: "", type: "monster", name: "Cube of Doom", loot: "0-10 Gold, 0-2 Arrows, 0-2 Slime Essence, Ironsword" },
  {
    hp: "222",
    exp: "430.51",
    abilities: "",
    type: "monster",
    name: "Pestilence Stinger",
    loot: "0-12 Gold, 0-3 Small Bones, 0-1 Plagued Scale, Small Skull, Spicy Stew, Spellbook: FierceThrust",
  },
  {
    hp: "170",
    exp: "213",
    type: "monster",
    name: "Giant Rat",
    abilities: "Melee (0-?), Leap (0-?)",
    loot: "0-7 Gold, 0-2 Cheese Slice, 0-2 Small Bones, Rat Tail, Cloth Vest, Yellow Beauty",
  },
  { hp: "93", exp: "114.29", name: "Goblin", type: "monster", abilities: "Melee (0-13)", loot: "0-5 Gold, Ragged Cloth" },
  {
    hp: "91",
    exp: "94.96",
    name: "Bandit",
    type: "monster",
    abilities: "Melee (0-5), Runs on red",
    loot: "0-5 Gold, 0-2 Bread Piece, Simple Bag, Knife, Cloth Vest, Leather Boots",
  },
  { hp: "46", exp: "40.68", type: "monster", name: "Skeleton", abilities: "Melee (0-9)", loot: "0-2 Gold, 0-2 Small Bones, Small Skull, Torch, Pumpkin, Buckler, Ironsword" },
  { exp: "", hp: "39", type: "monster", loot: "Lamb Meat", name: "Black Sheep", abilities: "Runs away" },
  { hp: "35", exp: "41", name: "Rat", abilities: "", type: "monster", loot: "0-3 Gold, 0-1 Cheese Slice" },
  { hp: "31", exp: "8.47", name: "Sheep", type: "monster", abilities: "Runs away", loot: "Lamb Meat, Wool" },
  { exp: "", hp: "27", name: "Lamb", type: "monster", loot: "Lamb Meat", abilities: "Runs away" },
  { hp: "23", loot: "", exp: "8.47", type: "monster", name: "Black Lamb", abilities: "Runs away" },
  { hp: "", exp: "", loot: "", abilities: "", type: "monster", name: "Amphitere" },
  { hp: "", exp: "", loot: "", abilities: "", type: "monster", name: "Rat Shipper" },
  { hp: "", exp: "", abilities: "", type: "monster", name: "Rubellus", loot: "Blue Gill" },
  { hp: "", exp: "", name: "Plea", abilities: "", type: "monster", loot: "0-7 Gold, Plea Toe, Spellbook: ShieldBlock, Broadsword, Old Gloves" },
  { hp: "", exp: "", abilities: "", type: "monster", name: "Tundra Rat", loot: "0-7 Gold, Leather Gloves, Leather Boots, Spangenhelm" },
  { hp: "", exp: "", abilities: "", type: "monster", name: "Pestilence Spawn", loot: "0-2 Bug Wings, Green Orb" },
  { hp: "", exp: "", abilities: "", name: "Digger", type: "monster", loot: "0-9 Gold, Ruby Necklace, Crystal Ring, Diamond Ring, Steel Ingot, Iron Ingot" },
  { hp: "", exp: "", abilities: "", type: "monster", name: "Pestilence Knight", loot: "0-308 Gold, 0-5 Plagued Scale, Pestilence Sword, Onyx Dagger" },
  { hp: "", exp: "", loot: "", abilities: "", type: "monster", name: "Profaner" },
  { hp: "", exp: "", loot: "", abilities: "", type: "monster", name: "The BroodMother" },
  { hp: "", exp: "", loot: "", abilities: "", type: "monster", name: "The BlackHat" },
  { hp: "", exp: "", loot: "", abilities: "", type: "monster", name: "Tomb Diviner" },
  { hp: "", exp: "", loot: "", abilities: "", type: "monster", name: "Deadly Webcap" },
  { hp: "", exp: "", loot: "", abilities: "", type: "monster", name: "Capozzi The Bandit" },
  { hp: "", exp: "", loot: "", abilities: "", type: "monster", name: "Cave Spider" },
  { hp: "", exp: "", loot: "", abilities: "", type: "monster", name: "Terror Spider" },
  { hp: "", exp: "300", name: "Monk", type: "monster", abilities: "Melee (0-?)", loot: "0-5 Gold, 0-2 Bread Piece, Old Gloves, Apple, Wooden Staff, Spellbook: Heal" },
  { hp: "", exp: "854", type: "monster", name: "Orc Infantry", abilities: "Melee (0-?), AOE (0-?)", loot: "0-5 Gold, 0-2 Bread Piece, Cloth Pants, Spangenhelm" },
  { hp: "", exp: "2180", type: "monster", name: "Minotaur", abilities: "Melee (0-?), Leap (0-?)", loot: "0-14 Gold, Chain Mail, Spangenhelm" },
  { hp: "", exp: "165.83", type: "monster", name: "Walking Boletus", loot: "White Mushroom, Boletus Piece", abilities: "Melee (0-?), Leap AOE (10-55)" },
  {
    hp: "",
    exp: "116.10",
    type: "monster",
    name: "Occultist Apprentice",
    abilities: "Melee (0-6), ConjureFire (0-18)",
    loot: "0-4 Gold, 0-2 Blueberries, Forsaken Cross, Worn Paper, Silver Dagger, Spellbook: ConjureFire",
  },
  {
    hp: "",
    exp: "199.16",
    type: "monster",
    name: "Occultist Acolyte",
    abilities: "Melee (0-6), Fireball (0-40)",
    loot: "0-4 Gold, Worn Paper, Small Mana Potion, Silver Ring, Gambeson, Dark Robe, Spellbook: Energybolt",
  },
  {
    hp: "",
    exp: "2494",
    type: "monster",
    name: "Orc General",
    abilities: "Melee (0-61), Explosive Dash 3x3 (0-?)",
    loot: "0-24 Gold, 0-2 Oranges, Brown Backpack, Meaty Stew, Longsword",
  },
  { hp: "", loot: "", exp: "1822", type: "monster", name: "Orc Shaman", abilities: "Ranged 3x3 Explosion (0-?), Ranged ConjureFire (0-?), Summons up to 2 Ancient Snakes" },

  // Book
  {
    type: "book",
    author: "Obtained",
    location: "Caravan",
    notes: "Licenced Chef Quest",
    name: "Cookbook - Spicy Stew",
    text: "To get water for your stew, you must first use a cauldron (or any other water source) with the bowl on your hand! Once you've got your water bowl, simply combine it with your cooked fish steak! And Voila! You've got your spicy stew!",
  },
  {
    type: "book",
    author: "Obtained",
    location: "Caravan",
    notes: "Licenced Chef Quest",
    name: "Cookbook - Fish Steak",
    text: "Make sure you got a knife to cut your fish! Make sure you grip it in your hands safely, and cut your fish by right - clicking on it! Once you've got your fish steaks, place them in your hands and use the stove to cook them!",
  },

  // Food
  { buffs: "", dropBy: "", type: "food", weight: "? oz", satiateTime: "-", requirements: "", name: "Empty Bowl", imageUrl: "/food/Wooden_bowl_empty.webp" },
  { buffs: "", weight: "", type: "food", satiateTime: "-", requirements: "", name: "Cheese Wheel", dropBy: "Cheese Wheel Quest", imageUrl: "/food/Cheese_wheel.webp" },
  { buffs: "", weight: "", type: "food", name: "Pumpkin", satiateTime: "-", requirements: "", dropBy: "Skeleton", imageUrl: "/food/Pumpkin.webp" },
  { buffs: "", dropBy: "", type: "food", name: "Potato", weight: "5 oz", satiateTime: "-", requirements: "", imageUrl: "/food/Raw_potato.webp" },
  { buffs: "", type: "food", name: "Wheat", weight: "1 oz", satiateTime: "-", requirements: "", imageUrl: "/food/Wheat.webp", dropBy: "What in the Barrel Quest" },
  {
    buffs: "",
    type: "food",
    weight: "11 oz",
    satiateTime: "-",
    requirements: "",
    name: "Lamb Meat",
    imageUrl: "/food/Raw_lamb.webp",
    dropBy: "Lamb, Sheep, Black Sheep, Cave Troll, Lamb Meat Quest",
  },
  { buffs: "", weight: "", type: "food", satiateTime: "?", requirements: "", name: "White Mushroom", dropBy: "Walking Boletus", imageUrl: "/food/White_mushroom.webp" },
  { buffs: "", weight: "", type: "food", name: "Apple", dropBy: "Monk", satiateTime: "?", requirements: "", imageUrl: "/food/Apple.webp" },
  { buffs: "", type: "food", name: "Orange", weight: "2.5 oz", requirements: "", satiateTime: "85", dropBy: "Orc General", imageUrl: "/food/Orange.webp" },
  { buffs: "", weight: "", type: "food", satiateTime: "", requirements: "", name: "Tofu Cube", dropBy: "Buy from Bessie", imageUrl: "/food/Tofu_cube.webp" },
  {
    buffs: "",
    type: "food",
    weight: "5 oz",
    satiateTime: "-",
    requirements: "",
    name: "Blue Gill",
    imageUrl: "/food/Blue_Gill.webp",
    dropBy: "Rubellus, Young Ampitere, Blue Gill Quest",
  },
  { buffs: "", dropBy: "", type: "food", weight: "6 oz", satiateTime: "-", requirements: "", name: "Red Breast", imageUrl: "/food/Red_Breast.webp" },
  { buffs: "", dropBy: "", type: "food", satiateTime: "-", weight: "4.8 oz", requirements: "", name: "Swamp Cod", imageUrl: "/food/Swamp_Cod.webp" },
  { buffs: "", weight: "", dropBy: "", type: "food", satiateTime: "", requirements: "", name: "Grilled Fish", imageUrl: "/food/Grilled_fish.webp" },
  { buffs: "", dropBy: "", type: "food", weight: "9 oz", satiateTime: "-", name: "Bread Loaf", requirements: "Dough + Pan", imageUrl: "/food/Bread_loaf.webp" },
  { dropBy: "", type: "food", weight: "3 oz", requirements: "", buffs: "speed +1", satiateTime: "300", name: "Dragonfruit", imageUrl: "/food/Dragonfruit.webp" },
  { dropBy: "", type: "food", weight: "5 oz", requirements: "", satiateTime: "325", name: "Spring Stew", buffs: "magic +2, speed +2", imageUrl: "/food/Spring_stew.webp" },
  {
    type: "food",
    weight: "5 oz",
    requirements: "",
    name: "Meaty Stew",
    satiateTime: "375",
    dropBy: "Orc General",
    buffs: "damage +2, skill +2",
    imageUrl: "/food/Meaty_stew.webp",
  },
  { dropBy: "", type: "food", weight: "6 oz", requirements: "", satiateTime: "375", name: "Spring Dish", buffs: "magic +1, speed +1", imageUrl: "/food/Spring_dish.webp" },
  { dropBy: "", type: "food", weight: "6 oz", requirements: "", name: "Spicy Rice", satiateTime: "425", buffs: "damage +6", imageUrl: "/food/Spicy_Rice.webp" },
  { buffs: "", type: "food", weight: "0.5 oz", requirements: "", satiateTime: "75", name: "Blueberries", dropBy: "Occultist Apprentice", imageUrl: "/food/Blueberries.webp" },

  // Recipes
  { buffs: "", dropBy: "", name: "Dough", type: "recipes", satiateTime: "-", weight: "3.5 oz", imageUrl: "/recipes/Dough.webp", requirements: "Wheat + Water Bowl" },
  {
    buffs: "",
    dropBy: "",
    weight: "? oz",
    type: "recipes",
    satiateTime: "-",
    name: "Water Bowl",
    imageUrl: "/recipes/Water_Bowl.webp",
    requirements: "Empty Bowl + Water Well or Cooking Pot",
  },
  {
    dropBy: "",
    type: "recipes",
    weight: "7.5 oz",
    satiateTime: "350",
    name: "Pumpkin Pie",
    buffs: "damage +2, magic +2",
    imageUrl: "/recipes/Pumpkin_pie.webp",
    requirements: "Dough Bowl + Pumpkin Slice",
  },
  { buffs: "", weight: "", dropBy: "", type: "recipes", satiateTime: "90", name: "Pumpkin Slice", requirements: "Pumpkin + Knife", imageUrl: "/recipes/Pumpkin_slice.webp" },
  {
    buffs: "",
    type: "recipes",
    weight: "1.1 oz",
    satiateTime: "100",
    name: "Bread Piece",
    requirements: "Bread Loaf + Knife",
    dropBy: "Bandit, Monk, Orc Infantry",
    imageUrl: "/recipes/Bread_Piece.webp",
  },
  {
    buffs: "",
    weight: "1 oz",
    type: "recipes",
    name: "Fish Steak",
    satiateTime: "105",
    dropBy: "Licensed Chef Quest",
    imageUrl: "/recipes/Fish_Steak.webp",
    requirements: "Any raw fish + Knife",
  },
  {
    buffs: "",
    weight: "2 oz",
    type: "recipes",
    satiateTime: "110",
    name: "Cheese Slice",
    requirements: "Cheese Wheel + Knife",
    dropBy: "Rat, Giant Rat, Tundra Rat",
    imageUrl: "/recipes/Cheese_Slice.webp",
  },
  {
    buffs: "",
    dropBy: "",
    weight: "1 oz",
    type: "recipes",
    satiateTime: "150",
    name: "Cooked White Mushroom",
    requirements: "Pan + White Mushroom",
    imageUrl: "/recipes/Cooked_mushroom.webp",
  },
  {
    buffs: "",
    dropBy: "",
    weight: "1 oz",
    type: "recipes",
    satiateTime: "165",
    name: "Cooked Fish Steak",
    imageUrl: "/recipes/Cooked_fish_fillet.webp",
    requirements: "Fish Steak + Stove or Campfire",
  },
  { buffs: "", dropBy: "", weight: "5 oz", type: "recipes", name: "Rice Dish", satiateTime: "165", requirements: "Water Bowl + Rice", imageUrl: "/recipes/Rice_Dish.webp" },
  { buffs: "", dropBy: "", type: "recipes", weight: "2.5 oz", satiateTime: "175", name: "Baked Potato", requirements: "Potato + Pan", imageUrl: "/recipes/Cooked_potato.webp" },
  { buffs: "", dropBy: "", weight: "1 oz", type: "recipes", satiateTime: "185", name: "Onion Rings", requirements: "Onion + Pan", imageUrl: "/recipes/Cooked_onion_rings.webp" },
  { buffs: "", dropBy: "", type: "recipes", weight: "10 oz", satiateTime: "200", name: "Cooked Lamb", requirements: "Lamb Meat", imageUrl: "/recipes/Cooked_lamb.webp" },
  { buffs: "", dropBy: "", weight: "1 oz", type: "recipes", satiateTime: "205", name: "Garlic Bread", requirements: "Onion + Bread Loaf", imageUrl: "/recipes/Garlic_Bread.webp" },
  {
    buffs: "",
    type: "recipes",
    weight: "1.2 oz",
    satiateTime: "250",
    name: "Grilled Cheese",
    dropBy: "Licensed Chef Quest",
    imageUrl: "/recipes/Grilled_cheese.webp",
    requirements: "Bread Piece + Cheese Slice",
  },
  {
    dropBy: "",
    type: "recipes",
    weight: "4.5 oz",
    satiateTime: "300",
    name: "Pumpkin Puree",
    buffs: "magic +1, skill +1",
    imageUrl: "/recipes/Pumpkin_Puree.webp",
    requirements: "Empty Bowl + Pumpkin Slice",
  },
  {
    buffs: "",
    dropBy: "",
    type: "recipes",
    name: "Sandwich",
    weight: "1.5 oz",
    satiateTime: "325",
    imageUrl: "/recipes/Sandwich.webp",
    requirements: "Bread Piece + Cooked Lamb or Bread Piece + Cooked Fish Steak",
  },
  {
    weight: "5 oz",
    type: "recipes",
    name: "Apple Pie",
    satiateTime: "350",
    buffs: "damage +2, magic +2",
    dropBy: "Licensed Chef Quest",
    requirements: "Dough Bowl + Apple",
    imageUrl: "/recipes/Apple_Pie.webp",
  },
  {
    dropBy: "",
    weight: "3 oz",
    type: "recipes",
    satiateTime: "350",
    name: "Blueberry Muffin",
    buffs: "damage +2, speed +2",
    requirements: "Dough Bowl + Blueberries",
    imageUrl: "/recipes/Blueberry_muffin.webp",
  },
  {
    dropBy: "",
    name: "Quiche",
    type: "recipes",
    weight: "2.5 oz",
    buffs: "speed +3",
    satiateTime: "350",
    imageUrl: "/recipes/Quiche.webp",
    requirements: "Dough Bowl + Cheese Slice",
  },
  {
    weight: "5 oz",
    type: "recipes",
    name: "Spicy Stew",
    satiateTime: "350",
    buffs: "damage +3",
    dropBy: "Licensed Chef Quest",
    imageUrl: "/recipes/Spicy_stew.webp",
    requirements: "Water Bowl + Cooked Fish Steak or Cheese Slice",
  },
  { buffs: "", dropBy: "", weight: "? oz", type: "recipes", satiateTime: "-", name: "Dough Bowl", requirements: "Empty Bowl + Dough", imageUrl: "/recipes/Dough_Bowl.webp" },
  {
    buffs: "",
    dropBy: "",
    weight: "? oz",
    type: "recipes",
    satiateTime: "-",
    name: "Water Bowl",
    imageUrl: "/recipes/Water_Bowl.webp",
    requirements: "Empty Bowl + Water Well or Cooking Pot",
  },

  // NPC
  {
    type: "npc",
    name: "Otis",
    location: "Caravan",
    sellTo: "Fish Steak (5 gp), Blue Gill (15 gp), Swamp Cod (35 gp), Red Breast (60 gp), Cooked Whole Fish (15 gp), Bowl of Water (6 gp), Rope (30 gp), Knife (10 gp)",
  },
  {
    type: "npc",
    name: "Hester",
    location: "Caravan",
    sellTo: "Simple Bag (5 gp), Brown Backpack (15 gp), Torch (3 gp), Health Potion (20 gp), Bread Piece (3 gp), Lantern (10 gp), Shovel (50 gp)",
  },
  {
    type: "npc",
    name: "Opal",
    location: "Caravan",
    sellTo: "Ironsword (50 gp), Buckler (50 gp), Kettle Helmet (45 gp), Gambeson (150 gp), Leather Cuisse (120 gp), Cloth Vest (35 gp), Old Gloves (50 gp), Spangenhelm (100 gp)",
  },
  {
    type: "npc",
    name: "Dewey",
    location: "Caravan",
    sellTo:
      "Cooked Fish Steak (10 gp), Cooked White Mushroom (8 gp), Spring Stew (15 gp), Spicy Rice (35 gp), Spring Dish (25 gp), Blueberry Muffin (45 gp), Iron Pan (20 gp), Wooden Bowl (5 gp)",
  },
  {
    type: "npc",
    name: "Gavin",
    location: "Caravan",
    sellTo: "Regeneration Ring (350 gp), Big Health Potion (60 gp), Cheese Wheel (100 gp), Orb (500 gp), Broadsword (500 gp), Berserk (500 gp), Taunt (150 gp)",
  },
  {
    type: "npc",
    name: "Zebulon",
    location: "Caravan",
    sellTo: "Wooden Staff (200 gp), ConjureFire (100 gp), Heal (50 gp), EnergyBolt (200 gp), Mana Potion (20 gp), Big Mana Potion (60 gp), Fireball (1200 gp), Haste (300 gp)",
  },
  {
    type: "npc",
    name: "Erastus",
    location: "Caravan",
    sellTo:
      "Arrow (1 gp), Wooden Bow (65 gp), Leather Bascinet (20 gp), Spellbook: PreciseShot (150 gp), Spellbook: Dash (300 gp), Leather Cloak (100 gp), Spellbook: ConjureArrow (200 gp)",
  },
  {
    type: "npc",
    name: "Burl",
    location: "Caravan",
    sellTo: "Ale Mug (10 gp), Grilled Cheese (25 gp), Bowl of Water (6 gp), Simple Bag (10 gp), Garlic Bread (25 gp), Onion Rings (15 gp)",
  },
  {
    type: "npc",
    name: "El Chad",
    location: "El Chad Village",
    sellTo:
      "House Counter (40 gp), House Box (50 gp), House Seat (20 gp), House Torch (100 gp), House Barrel (45 gp), House Chest (100 gp), House Chair (20 gp), House Depot (500 gp)",
  },
  {
    type: "npc",
    name: "Wolfram",
    location: "Capital, Docks",
    sellTo: "Simple Bag (10 gp), Knife (10 gp), Blue Gill (10 gp), Apple (15 gp), Paper (5 gp), Quill (5 gp), Crowbar (50 gp)",
  },
  { type: "npc", name: "Lurleen", location: "Capital", sellTo: "Yellow Beauty (50 gp), Hero Flower (75 gp), Kings Nose (50 gp), Rose (20 gp), Apple Pie (50 gp), Apple (10 gp)" },
  {
    type: "npc",
    name: "Mabel",
    location: "Capital",
    sellTo: "Simple Bag (50 gp), Brown Backpack (15 gp), Torch (5 gp), Empty Bowl (3 gp), Bread Piece (3 gp), Pan (15 gp), Apple (8 gp), Shovel (40 gp)",
  },
  { type: "npc", name: "Maxwell", location: "Capital, Temple", sellTo: "Bread Piece (3 gp), Water Bowl (5 gp), Heal (50 gp), Light (35 gp)" },
  {
    type: "npc",
    name: "Maude",
    location: "Capital, Trading District (upstairs)",
    sellTo: "Cloth Pants (10 gp), Blue Book (12 gp), Green Book (20 gp), Red Notebook (15 gp), Yellow Notebook (25 gp), Light (30 gp), LightMissile (150 gp), Heal (45 gp)",
  },
  { type: "npc", name: "Benedict", location: "Capital Library", sellTo: "Simple Garment (10 gp), Leather Cuisse (100 gp), Pocket Watch (30 gp), Wool (50 gp), Candle (15 gp)" },
  {
    type: "npc",
    name: "Reginald",
    location: "Capital Housing Area",
    sellTo:
      "House Counter (40 gp), House Box (50 gp), House Seat (20 gp), House Torch (100 gp), House Barrel (45 gp), House Chest (100 gp), House Chair (20 gp), House Depot (500 gp)",
  },
  { type: "npc", name: "Edmund", location: "Tutorial Village", sellTo: "Simple Bag (5 gp), Bread Loaf (35 gp), Wooden Bowl (5 gp), Holy (150 gp), Light (35 gp)" },
  { type: "npc", name: "Bessie", location: "Swamp", sellTo: "Nightshade (80 gp), Rat Tail (30 gp), Rope (25 gp), Tofu Block (7 gp), Cloth Pants (5 gp)" },
  {
    type: "npc",
    name: "Violet",
    location: "Swamp",
    sellTo: "Mana Potion (15 gp), Health Potion (15 gp), Big Health Potion (35 gp), Big Mana Potion (35 gp), EnergyHull (1200 gp), Lightning (550 gp)",
  },
  { type: "npc", name: "Eofor", sellTo: "Rogue", location: "East of The Caravan" },
  { type: "npc", name: "Gareth", sellTo: "Knight", location: "East of Tutorial Area" },
];
